version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports: 
      - 80:80
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'
  
  php:
    container_name: php
    build:
      context: docker/php/
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORt=3306